homepage:
    path: /
    defaults:
        _controller:  FrameworkBundle:Redirect:urlRedirect
        path: /api/doc
        permanent: true
newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
