newsletter_homepage:
    path:     /
    defaults: { _controller: NewsletterBundle:Default:index }

newsletter:
    resource: "@NewsletterBundle/Controller/NewsletterController.php"
    prefix: /api/
    type: rest
