services:
  newsletter.entity.article_repository:
    class: NewsletterBundle\Repository\ArticleRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
        - NewsletterBundle\Entity\Article